import Head from 'next/head'
import Image from 'next/image'
import Banner from '../Components/Banner'
import Footer from '../Components/Footer'
import FooterBanner from '../Components/FooterBanner'
import Header from '../Components/Header'
import ImageCard from '../Components/ImageCard'
import Place from '../Components/place'

export default function Home({places, images}) {

  return (
    <div className=''>
      <Head>
        <title>Reserved your room before land!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header/>
      <Banner/>

      <main className='max-w-5xl mx-auto px-8 sm:px-17 '>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold'>Explore Nearby</h2>
         
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {places?.map(place => <Place 
          key={place._id}
          place = {place}
          /> )}
          </div>
        </section>
        <section>
          <h2 className='text-4xl font-semibold py-8'>Explore Places & Live Anywhere</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide  p-3 -ml-3'>
            {
              images?.map(image => <ImageCard 
                key={image._id}
                image = {image}
              /> )
            }
          </div>
        </section>
        <FooterBanner/>
      </main>
      <footer>
        <Footer/>
      </footer>
    </div>
  )
}

export async function getStaticProps(){
  const places = await fetch('https://whispering-tundra-09529.herokuapp.com/places').then(res =>res.json());

  const images = await fetch('https://whispering-tundra-09529.herokuapp.com/images').then(res=> res.json())

  return {
    props:{
      places,
      images
    }
  }
}
