import Head from 'next/head'
import Header from '../Components/Header'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Reserved your room before land!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <Header/>

      {/* Header  */}
      {/* Banner  */}
    </div>
  )
}
